name: Verify Member
outputs:
  isTSCMember:
    description: 'Verify Member'
    value: ${{steps.verify_member.outputs.isTSCMember}}
inputs:
  authorName:
    description: 'Name of the Author'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install the dependencies
      run: npm install js-yaml
      shell: bash
      
    - name: Verify TSC Member
      id: verify_member
      uses: actions/github-script@v6
      with:
        script: |
           const yaml = require('js-yaml');
           const fs = require('fs');
           const commenterName = '${{inputs.authorName}}';
           let isTSCMember = false;
           try {
               // Load YAML file
               const data = yaml.load(fs.readFileSync('MAINTAINERS.yaml', 'utf8'));
               // Iterate over each person object
               data.forEach(person => {
                   // Check if the person is a TSC member or not
                   if (person.isTscMember && person.github == commenterName) {
                       isTSCMember = true;
                       
                   }
               });
           } catch (e) {
               console.log(e);
           }
          core.setOutput('isTSCMember', isTSCMember);