name: Verification of the Vote

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Verify the person
        id: verify_member
        uses: ./.github/actions/verifyMember
        with:
          authorName: "${{github.event.comment.user.login}}"

      - name: Set Output to Environment Variable
        run: echo "IS_TSC_MEMBER=${{ steps.verify_member.outputs.version }}" >> $GITHUB_ENV

      - name: Checking the person authenticity for vote.
        if:  contains(github.event.comment.body, '/vote') || contains(github.event.comment.body, '/cancel-vote')
        uses: actions/github-script@v6
        with:
          script: |
            const isTSCMember = ${{env.IS_TSC_MEMBER}};
             if (!isTSCMember) {
                const commentText = `User ❌ @${{ github.actor }} is not a [TSC Member](https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json).`;
                 console.log(`User ❌ @${{ github.actor }} is not a TSC Member`);
                 github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                 body: commentText
               });
             } else if('${{github.actor}}' != 'git-vote[bot]') {
                console.log(`User ✅ @${{ github.actor }} is a TSC Member`);
            }

      - name: Add the label
        if: (contains(github.event.comment.body, '/cancel-vote') || contains(github.event.comment.body, '/vote')) && env.IS_TSC_MEMBER =='true'
        run: |
          if [ "${{ github.event.comment.body }}" == "/cancel-vote" ]; then
            if [ "${{ github.event_name }}" != "pull_request" ]; then
              gh issue edit ${{ github.event.issue.number }} --remove-label "vote"
            else
              gh pr edit ${{ github.event.issue.number }} --remove-label "vote"
            fi
          fi
          if [ "${{ github.event.comment.body }}" == "/vote" ]; then
            if [ "${{ github.event_name }}" != "pull_request" ]; then
              gh issue edit ${{ github.event.issue.number }} --add-label "vote"
            else
              gh pr edit ${{ github.event.issue.number }} --add-label "vote"
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}