name: Vote Tracker

on:
  issue_comment:
    types: [created]

jobs:
  track-vote:
    if: ${{ github.actor == 'git-vote[bot]' && contains(github.event.comment.body, 'Vote closed')}}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing Module
        run: npm install js-yaml@4.1.0
        shell: bash

      - name: Run GitHub Script
        id: vote_tracker
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/vote_tracker.js');
            await script({ github, context, core });
          

      - name: Create Pull Request to update Vote Tracking Details
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # uses 5.0.2 https://github.com/peter-evans/create-pull-request/releases/tag/v5.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore: update vote tracking details'
          committer: asyncapi-bot <info@asyncapi.io>
          author: asyncapi-bot <info@asyncapi.io>
          title: 'chore: vote tracking details'
          body: 'Update the votetrackingDetails.md and votetracking.json'
          branch: vote-trackingupdate/${{ github.job }}
